site_name: Indexify

repo_url: https://github.com/diptanu/indexify
repo_name: diptanu/indexify
edit_uri: edit/main/docs/docs
copyright: Copyright &copy; 2023 Indexify

markdown_extensions:
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets


nav:
  - Home: 'index.md'
  - Getting Started: 'getting_started.md'
  - Overview: 'overview.md'
  - APIs:
    - Overview: 'apis/index.md'
    - Data Repository: 'apis/data_repository.md'
    - Retrieval: 'apis/retrieval.md'
    - Memory: 'apis/memory.md'
    - Embeddings: 'apis/embeddings.md'
  - Configuration: 'configuration.md'
  - Python SDK: python_sdk.ipynb
  - Deployment: 'deployment.md'
  - Develop Indexify: 'develop.md'
  - Integrations:
    - Langchain: 'integrations/langchain.md'
    - Haystack: 'integrations/haystack.md'
plugins: 
  - mkdocs-jupyter

theme:
  name: material
  icon:
    repo: fontawesome/brands/github
    edit: material/pencil 
    view: material/eye

  features:
    - content.action.edit
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - navigation.expand
    - content.code.copy
    - content.code.annotate


  palette: 
    - scheme: default
      primary: light blue
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

extra:
  generator: false
  analytics:
     provider: google
     property: G-6BCQ6Z265W
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.gg/mrXrq3DmV8
      name: Indexify Discord Community
    - icon: fontawesome/solid/paper-plane
      link: mailto:<diptanuc@gmail.com>
      name: Email
      
